// P7 — production server. `next start` cannot serve TLS, so this thin wrapper
// picks HTTP or HTTPS at boot from ~/.easyagent/settings.json (`https: true`
// + the cert generated by the in-app toggle). Plain Node — not bundled by Next.

import { createServer as createHttp } from "node:http";
import { createServer as createHttps } from "node:https";
import { readFileSync } from "node:fs";
import { homedir } from "node:os";
import { join } from "node:path";
import next from "next";

const host = process.env.HOST || "127.0.0.1";
const port = parseInt(process.env.PORT || "3000", 10);
const dir = process.env.EASYAGENT_DIR || join(homedir(), ".easyagent");

let useTls = false;
let cred = null;
try {
  useTls = JSON.parse(readFileSync(join(dir, "settings.json"), "utf8")).https === true;
} catch {
  /* no settings yet → HTTP */
}
if (useTls) {
  try {
    cred = {
      key: readFileSync(join(dir, "tls", "key.pem")),
      cert: readFileSync(join(dir, "tls", "cert.pem")),
    };
  } catch {
    useTls = false;
    console.warn("[easyagent] HTTPS is enabled but the certificate is missing - falling back to HTTP.");
  }
}
// Routes read this to mark the session cookie Secure.
process.env.EASYAGENT_HTTPS = useTls ? "1" : "0";

const app = next({ dev: false, hostname: host, port });
const handle = app.getRequestHandler();
await app.prepare();

const server = useTls ? createHttps(cred, handle) : createHttp(handle);
server.listen(port, host, () => {
  console.log(`> easyagent ready at ${useTls ? "https" : "http"}://${host}:${port}`);
});
